-- 선택 사항: 수강문의와 게시판을 붙일 때 사용하는 기본 스키마
create table if not exists contact_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  inquiry_type text,
  message text,
  created_at timestamptz default now()
);

create table if not exists board_posts (
  id bigint generated by default as identity primary key,
  category text not null default 'notice',
  title text not null,
  content text not null,
  author text not null default '관리자',
  views integer not null default 0,
  created_at timestamptz default now()
);
