-- Supabase SQL Editor에서 실행하세요.

create table if not exists contact_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  inquiry_type text,
  message text,
  created_at timestamp with time zone default now()
);

create table if not exists board_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null check (category in ('notice', 'qna', 'resource', 'case')),
  author text not null,
  content text not null,
  views integer default 0,
  created_at timestamp with time zone default now()
);

alter table contact_inquiries enable row level security;
alter table board_posts enable row level security;

-- 문의 등록: 방문자가 insert 가능
create policy "Anyone can insert contact inquiries"
on contact_inquiries
for insert
with check (true);

-- 게시글 읽기: 방문자가 select 가능
create policy "Anyone can read board posts"
on board_posts
for select
using (true);

-- 게시글 등록: 방문자가 insert 가능
-- 운영 사이트에서는 관리자 로그인 후 insert하도록 바꾸는 것을 권장합니다.
create policy "Anyone can insert board posts"
on board_posts
for insert
with check (true);

insert into board_posts (title, category, author, content, views)
values
('AI 전산감사 실무 과정 수강 안내', 'notice', '관리자', 'AI 전산감사 실무 과정 모집 안내입니다.', 0),
('영수증 OCR 자동분개 실습 자료', 'resource', '강사', '수업에서 사용하는 OCR 실습 자료 안내입니다.', 0),
('회계 지식이 없어도 수강 가능한가요?', 'qna', '수강문의', '입문 단계에서 회계 데이터 구조부터 설명합니다.', 0)
on conflict do nothing;
