-- 선택 사항: 문의 폼을 Supabase로 연결할 때 사용할 수 있는 테이블 예시
create table if not exists contact_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  type text,
  message text,
  created_at timestamptz default now()
);

alter table contact_inquiries enable row level security;

-- 실제 운영 전에는 관리자 정책을 별도로 설정하세요.
create policy "allow_insert_contact_inquiries"
on contact_inquiries for insert
to anon
with check (true);
